# GNUstep makefile

-include ../../../config.make
include $(GNUSTEP_MAKEFILES)/common.make

WOAPP_NAME = HelloWorld

HelloWorld_OBJC_FILES += HelloWorld.m Main.m
HelloWorld_COMPONENTS += Main.wo

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/woapp.make
-include GNUmakefile.postamble
