# GNUstep makefile

include ../config.make
include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS += SBJson

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
