# compile settings

APPSERVER="../.."

ADDITIONAL_LIB_DIRS += \
	-L$(APPSERVER)/NGObjWeb/$(GNUSTEP_OBJ_DIR)

# static references required for Mach linker

ADDITIONAL_TOOL_LIBS += \
	-lEOControl	\
	-lDOM -lXmlRpc -lSaxObjC

ADDITIONAL_LIB_DIRS += -L/usr/local/lib -L/usr/lib
