# GNUstep makefile

-include ../../../config.make
include $(GNUSTEP_MAKEFILES)/common.make

WOAPP_NAME = SoCookieAuth

SoCookieAuth_OBJC_FILES += Application.m Main.m
SoCookieAuth_COMPONENTS += Main.wo

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/woapp.make
-include GNUmakefile.postamble
