#
# GNUmakefile
# ÇPROJECTNAMEÈ
#
# Created by ÇUSERNAMEÈ on ÇDATEÈ
#

include $(GNUSTEP_MAKEFILES)/common.make

WOAPP_NAME = ÇPROJECTNAMEÈ

ÇPROJECTNAMEÈ_OBJC_FILES =	\
	Application.m		\
	Session.m 		\
	DirectAction.m		\

ÇPROJECTNAMEÈ_OBJC_FILES +=	\
	Main.m			\

ÇPROJECTNAMEÈ_OBJC_FILES +=	\
	ÇPROJECTNAMEÈ_main.m


ÇPROJECTNAMEÈ_COMPONENTS =	\
	Main.wo

ÇPROJECTNAMEÈ_RESOURCE_FILES =	\


ÇPROJECTNAMEÈ_LANGUAGES =	\
	English			\


ÇPROJECTNAMEÈ_LOCALIZED_RESOURCE_FILES	=	\


ÇPROJECTNAMEÈ_WEBSERVER_RESOURCE_FILES := \
	$(shell find WebServerResources -type f -print)

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/woapp.make
-include GNUmakefile.postamble
