# compile settings

ADDITIONAL_INCLUDE_DIRS += \
	-I. -I..	\
	-I../NGObjWeb

ADDITIONAL_LIB_DIRS += \
	-L../NGObjWeb/$(GNUSTEP_OBJ_DIR)	\

parsedav_TOOL_LIBS += \
	-lNGObjWeb	\
	-lNGMime	\
	-lNGStreams -lNGExtensions -lEOControl \
	-lDOM -lXmlRpc -lSaxObjC

SYSTEM_LIB_DIR += $(CONFIGURE_SYSTEM_LIB_DIR)
