# GNUstep makefile

-include ../../../config.make
include $(GNUSTEP_MAKEFILES)/common.make

WOAPP_NAME = WOxExtTest

WOxExtTest_OBJC_FILES += \
	WOxExtTest.m		   \
	Main.m			   \
	Frame.m			   \
	PanelContent.m  \
	\
	ValidatedField.m	   \
	Switch.m                   \
	Table.m                    \
	TableView.m                \
	DnD.m	                   \
	TreeView.m                 \
	Browser.m                  \
	ImageFlyover.m             \
	DirectAction.m             \
	TabPanel.m                 \
	KeyValueConditional.m      \
	TabView.m                  \
	AlertPanel.m               \
	ConfirmPanel.m             \
	TextFlyover.m              \
	ModalWindow.m              \
	CollapsibleContent.m       \
	DictionaryRepetition.m     \
	ThresholdColoredNumber.m   \
	CollapsibleContentExt.m    \
	RadioButtonMatrix.m        \
	CheckBoxMatrix.m           \
	PageView.m                 \
	WeekOverview.m             \
	WeekColumnView.m           \
	MonthOverview.m            \
	TableMatrix.m              \
	ShiftClick.m               \
	TimeField.m                \
	DateField.m                \
	CalendarField.m            \
	RichString.m               \
	QualifierConditional.m     \

WOxExtTest_RESOURCE_FILES += \
	Resources/TableView.plist       \
	Resources/TreeView.plist        \
	Resources/Dictionary.plist      \
	Resources/appointments.plist    \
	\
	Main.wox			\
	Frame.wox			\
	ValidatedField.wox		\
	Switch.wox			\
	Table.wox			\
	DnD.wox				\
	TableView.wox			\
	TreeView.wox			\
	Browser.wox			\
	ImageFlyover.wox		\
	TabPanel.wox			\
	KeyValueConditional.wox		\
	TabView.wox			\
	AlertPanel.wox			\
	ConfirmPanel.wox		\
	TextFlyover.wox			\
	CollapsibleContent.wox		\
	DictionaryRepetition.wox	\
	ThresholdColoredNumber.wox	\
	CollapsibleContentExt.wox	\
	RadioButtonMatrix.wox		\
	CheckBoxMatrix.wox		\
	PageView.wox			\
	WeekOverview.wox		\
	WeekColumnView.wox		\
	MonthOverview.wox		\
	ShiftClick.wox			\
	TimeField.wox			\
	DateField.wox			\
	CalendarField.wox		\
	RichString.wox			\
	VarString.wox			\
	QualifierConditional.wox        \

WOxExtTest_WEBSERVER_RESOURCE_FILES = \
	favicon.ico		      \
	site.css		      \
	WebServerResources/*.gif      \

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/woapp.make
-include GNUmakefile.postamble
