# GNUstep makefile

include ../../config.make
include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = \
	saxxml		\
	xmln		\
	rss2plist1	\
	rss2plist2	\
	rssparse	\
	domxml		\
	testqp		\

rss2plist1_OBJC_FILES = rss2plist1.m
rss2plist1_INSTALL_DIR = $(SOPE_TOOLS)/
rss2plist2_OBJC_FILES = rss2plist2.m
rss2plist2_INSTALL_DIR = $(SOPE_TOOLS)/
rssparse_OBJC_FILES   = rssparse.m
rssparse_INSTALL_DIR = $(SOPE_TOOLS)/
saxxml_OBJC_FILES     = saxxml.m
saxxml_INSTALL_DIR = $(SOPE_TOOLS)/
xmln_OBJC_FILES       = xmln.m
xmln_INSTALL_DIR = $(SOPE_TOOLS)/
domxml_OBJC_FILES     = domxml.m
domxml_INSTALL_DIR = $(SOPE_TOOLS)/
testqp_OBJC_FILES     = testqp.m
testqp_INSTALL_DIR = $(SOPE_TOOLS)/

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
