# GNUstep makefile

include ../../config.make
include $(GNUSTEP_MAKEFILES)/common.make
include ../Version
include ./Version

BUNDLE_NAME        = pyxSAXDriver
BUNDLE_EXTENSION   = .sax
BUNDLE_INSTALL_DIR = ${SOPE_SAXDRIVERS}/

pyxSAXDriver_OBJC_FILES = pyxSAXDriver.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble
