ADDITIONAL_INCLUDE_DIRS += -I. -I./WebDAV

ADDITIONAL_TOOL_LIBS += -lNGiCal

ifeq ($(FOUNDATION_LIB),apple)
ADDITIONAL_TOOL_LIBS += \
	-lEOControl	\
	-lXmlRpc -lDOM -lSaxObjC
else
ifneq ($(findstring openbsd, $(GNUSTEP_TARGET_OS)), openbsd)
ADDITIONAL_TOOL_LIBS += -lcrypt
endif
endif

SYSTEM_LIB_DIR += -L/usr/local/lib -L/usr/lib
