# $Id: GNUmakefile,v 1.1 2004/06/14 14:59:26 helge Exp $

include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = TestApp

TestApp_OBJC_FILES = \
	TestApp.m	\

TestApp_RESOURCE_FILES = \

include $(GNUSTEP_MAKEFILES)/bundle.make
