# GNUstep makefile

-include ../../../config.make
include $(GNUSTEP_MAKEFILES)/common.make

WOAPP_NAME = TestPrototype

TestPrototype_OBJC_FILES += TestPrototype.m Main.m
TestPrototype_COMPONENTS += Main.wo

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/woapp.make
-include GNUmakefile.postamble
