.\"GNUstep(7) man page
.\"put together by Martin Brecher <martin@gnustep.de>
.\"
.\"Process this file with
.\"groff -man -Tascii GNUstep.7
.\"
.TH GNUSTEP 7 "August 2003" GNUstep "GNUstep System Manual"
.SH NAME
GNUstep \- A free implementation of the OpenStep standard

.SH DESCRIPTION
GNUstep provides an Object-Oriented application development framework 
and toolset for use on a wide variety of computer platforms. 
GNUstep is based on the original OpenStep specification provided by 
NeXT, Inc. (now Apple).
.P
GNUstep is written in Objective-C, an object-oriented superset of the C 
programming language, similar to SmallTalk. However there exist a number
of brigdes and interfaces to develop GNUstep programs using other languages
like JAVA or Ruby.

.P
.B The GNUstep Core System
.P
The GNUstep core system consists of the following parts:
.IP gnustep-make
	A set of scripts and makefiles that heavily ease the 
	creation and maintenance of software projects.
.IP gnustep-base
	The FoundationKit libraries for non-GUI tools providing 
	everything from string
	and array classes, filemanager classes to distributed objects.
.IP gnustep-gui
	The ApplicationKit containing widgets, workspace classes and 
	means for
	applications to interact with the user. This is the frontend of
	GNUstep's GUI part.
.IP gnustep-back
	This is the backend of GNUstep's GUI part which does the actual
	rendering and event handling. It acts as a layer between 
	gnustep-gui and the operating/drawing system. Backends exist
	for X11 (one using libart, one using xlib drawing) and win32.

Apart from the above, there exist a number of addon libraries, like Renaissance
which allows developers to specify an application's user interface in xml.
For database access, there is gdl2 - the GNUstep Database Library.
Please refer to the GNUstep website for more information.


GNUstep is self-containing. That means that all GNUstep applications, tools,
libraries and add-ons are installed into the GNUstep directory hierarchy.
There are four domains which are searched for files: the System domain, which
should only contain the core system files, the Local domain which stores all
that has later been installed on the system, the Network domain which should
be used for importing data from a remote system, and the User domain which resides in the user's home directory (mostly ~/GNUstep). 
See the filesystem.texi document for more information.

.P
.B Some Basic Terms:

.P
.B Tools and Applications
.P
In the world of GNUstep the term
.I tool
refers to command line programs whereas 
.I applications 
are fully fledged GUI programs. 
Naturally, 
.I tools
reside in the domains' Tools folder, 
.I applications
can be
found in the domains' Applications folder.

Applications are either launched using the openapp command or from the
Workspace.


.P
.B Services
.P
In GNUstep applications globally offer functionality to other applications
through 
.I services
. They can be reached through the Services menu entry in an
application's main menu.
Apart from 
.I services
offered by applications, there may
be programs whose sole purpose is the offering of services. They can be found
in the domains' Libary/Services folders.

.P
.B The Workspace
.P
The central place of the user interface is the 
.I Workspace 
or 
.I Workspace Manager
which acts as an interface between the user and parts of the system like
files, processes, etc. The GWorkspace application provides this functionality
in GNUstep. See the GWorkspace website for more details.

.P
.P
.B Getting More Help
.P
Most discussion and support is taking place on the GNUstep mailinglists
<http://www.gnustep.org/information/gethelp.html>. Additionally, most larger
projects have their own mailing lists. Consult the appropriate websites for
details.
.P
Alternatively you are invited to join the #GNUstep IRC channel on 
FreeNode (irc.freenode.net).
.P
.SH SEE ALSO
gcc(1), gdnc(1), gdomap(8), gopen(1), gpbs(1), make(1), openapp(1)
.PP
.B GNUstep Websites:
.PP 
Official GNUstep website <http://www.gnustep.org/> - 
GNUstep Wiki (lots of useful information) <http://wiki.gnustep.org/> - 
GNUstep Project Page <http://savannah.gnu.org/projects/gnustep/>  -
GNUstep Community Page <http://www.gnustep.net/> -
GNUstep Documentation Library <http://gnustep.made-it.com/> -
GNUstep Build Guide <http://gnustep.made-it.com/BuildGuide/>
.PP
Collaboration World <http://www.collaboration-world.com/> -
GNUstep.de <http://www.gnustep.de/> - 
GNUstep.it <http://www.gnustep.it/> -
GNUstep.us <http://www.gnustep.us/> -
GWorkspace Website <http://www.gnustep.it/enrico/gworkspace/>
.PP
.B Mailinglists:
.PP
<http://www.gnu.org/software/gnustep/information/gethelp.html> -
Archives can be found at <http://mail.gnu.org/archive/html/>
.P
.SH AUTHORS
GNUstep is developed and maintained by a large number of people. Please
see <http://www.gnustep.org/developers/whoiswho.html> for a list.
.PP
GWorkspace is developed by Enrico Sersale. Please see the GWorkspace Website
for details.
.PP
This man page was written by Martin Brecher <martin@mb-itconsulting.com>.
