# $Id: GNUmakefile 1 2004-08-20 10:08:27Z znek $

include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = woslash

woslash_OBJC_FILES = \
	woslash.m	\
	SlashDotStory.m	\

woslash_TOOL_LIBS += -lNGObjWeb -lWOXML

include $(GNUSTEP_MAKEFILES)/tool.make
